from .download_content_interface import DownloadContentInterface
from .download_essential_interface import DownloadEssentialInterface
from .download_manager_interface import DownloadManagerInterface
from .download_playlist_interface import DownloadPlaylistInterface
from .download_video_interface import DownloadVideoInterface
